custom_tags = [
    "O", "B-INVOICE_NUMBER", "I-INVOICE_NUMBER",
    "B-INVOICE_DATE", "I-INVOICE_DATE", "B-DUE_DATE", "I-DUE_DATE",
    "B-CUSTOMER_PO", "I-CUSTOMER_PO", "B-VENDOR_NAME", "I-VENDOR_NAME",
    "B-VENDOR_ADDRESS", "I-VENDOR_ADDRESS", "B-VENDOR_PHONE", "I-VENDOR_PHONE",
    "B-VENDOR_EMAIL", "I-VENDOR_EMAIL", "B-VENDOR_WEBSITE", "I-VENDOR_WEBSITE",
    "B-CUSTOMER_NAME", "I-CUSTOMER_NAME", "B-CUSTOMER_ADDRESS", "I-CUSTOMER_ADDRESS",
    "B-CUSTOMER_PHONE", "I-CUSTOMER_PHONE", "B-CUSTOMER_EMAIL", "I-CUSTOMER_EMAIL",
    "B-ITEM_DESCRIPTION", "I-ITEM_DESCRIPTION", "B-QUANTITY", "B-UNIT_PRICE",
    "B-TOTAL_PRICE", "B-SUBTOTAL", "I-SUBTOTAL", "B-TAX_AMOUNT", "I-TAX_AMOUNT",
    "B-TOTAL_AMOUNT_DUE", "I-TOTAL_AMOUNT_DUE", "B-PAYMENT_TERMS", "I-PAYMENT_TERMS",
    "B-PAYMENT_METHOD", "I-PAYMENT_METHOD", "B-BANK_DETAILS", "I-BANK_DETAILS",
    "B-NOTES", "I-NOTES", "B-GST", "B-GSTIN", "I-GSTIN", "B-CGST", "B-SGST", "B-IGST",
    "B-AMOUNT", "I-AMOUNT", "B-SUB-TOTAL", "I-SUB-TOTAL"
]
